[mcp]          
server_url = "Enter your mcp url"

[embedding]          
api_key = "Enter your api key (match url : https://api.siliconflow.cn/v1/embeddings)"
cache   = "embedding_cache.pkl"

[template]
api_base = "https://ark.cn-beijing.volces.com/api/v3"
api_key  = "Enter your api key"


[openai]             
api_base = "https://api.openai-proxy.org/v1"
api_key  = "Enter your api key"

[deepseek]          
api_base = "https://api.deepseek.com"
api_key  = "Enter your api key"